/*******************************************************************************
 * File generated from the UML::BubbleSort uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of BubbleSort.
 * 
 * @author 
 */
public class BubbleSort extends SortAlgorithm {
	// Start of user code (user defined attributes for BubbleSort)

	// End of user code

	/**
	 * The constructor.
	 */
	public BubbleSort() {
		// Start of user code constructor for BubbleSort)
		super();
		// End of user code
	}

	/**
	 * Description of the method executeNextSwap.
	 * @return 
	 */
	public Integer executeNextSwap() {
		// Start of user code for method executeNextSwap
		Integer executeNextSwap = Integer.valueOf(0);
		return executeNextSwap;
		// End of user code
	}

	// Start of user code (user defined methods for BubbleSort)

	// End of user code

}
