/*******************************************************************************
 * File generated from the UML::Controller uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Controller.
 * 
 * @author 
 */
public abstract class Controller {
	/**
	 * Description of the property mModel.
	 */
	protected iController mModel = null;

	/**
	 * Description of the property icontroller.
	 */
	public iController icontroller = null;

	// Start of user code (user defined attributes for Controller)

	// End of user code

	/**
	 * The constructor.
	 */
	public Controller() {
		// Start of user code constructor for Controller)
		super();
		// End of user code
	}

	// Start of user code (user defined methods for Controller)

	// End of user code

}
