/*******************************************************************************
 * File generated from the UML::eSortAlgorithm uml Enumeration
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of eSortAlgorithm.
 * 
 * @author 
 */
public enum ESortAlgorithm {
							/**
							 * Description of eSortBubble.
							 */
							eSortBubble,

							/**
							 * Description of eSortInsert.
							 */
							eSortInsert,

	// Start of user code (user defined enum literals for eSortAlgorithm)

	// End of user code
}
