/*******************************************************************************
 * File generated from the UML::exIsSorted uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of exIsSorted.
 * 
 * @author 
 */
public class exIsSorted {
	// Start of user code (user defined attributes for exIsSorted)

	// End of user code

	/**
	 * The constructor.
	 */
	public exIsSorted() {
		// Start of user code constructor for exIsSorted)
		super();
		// End of user code
	}

	// Start of user code (user defined methods for exIsSorted)

	// End of user code

}
