/*******************************************************************************
 * File generated from the UML::GUI uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of GUI.
 * 
 * @author 
 */
public abstract class GUI {
	/**
	 * Description of the property mView.
	 */
	protected Object mView = ;

	/**
	 * Description of the property view.
	 */
	public View view = null;

	/**
	 * Description of the property controller.
	 */
	public Controller controller = null;

	// Start of user code (user defined attributes for GUI)

	// End of user code

	/**
	 * The constructor.
	 */
	public GUI() {
		// Start of user code constructor for GUI)
		super();
		// End of user code
	}

	// Start of user code (user defined methods for GUI)

	// End of user code

}
