/*******************************************************************************
 * File generated from the UML::iController uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of iController.
 * 
 * @author 
 */
public interface iController {
	// Start of user code (user defined attributes for iController)

	// End of user code

	/**
	 * Description of the method sort.
	 */
	public void sort();

	/**
	 * Description of the method setSortAlgorithm.
	 * @param iAlgorithm 
	 */
	public void setSortAlgorithm(eSortAlgorithm iAlgorithm);

	// Start of user code (user defined methods for iController)

	// End of user code

}
