/*******************************************************************************
 * File generated from the UML::iModelPresent uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of iModelPresent.
 * 
 * @author 
 */
public interface iModelPresent {
	// Start of user code (user defined attributes for iModelPresent)

	// End of user code

	/**
	 * Description of the method getLastSwapPos.
	 * @return 
	 */
	public Integer getLastSwapPos();

	/**
	 * Description of the method getList.
	 * @return 
	 */
	public Integer getList();

	/**
	 * Description of the method getElement.
	 * @param iPos 
	 * @return 
	 */
	public Integer getElement(Integer iPos);

	// Start of user code (user defined methods for iModelPresent)

	// End of user code

}
