/*******************************************************************************
 * File generated from the UML::InsertionSort uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of InsertionSort.
 * 
 * @author 
 */
public class InsertionSort extends SortAlgorithm {
	// Start of user code (user defined attributes for InsertionSort)

	// End of user code

	/**
	 * The constructor.
	 */
	public InsertionSort() {
		// Start of user code constructor for InsertionSort)
		super();
		// End of user code
	}

	/**
	 * Description of the method executeNextSwap.
	 * @return 
	 */
	public Integer executeNextSwap() {
		// Start of user code for method executeNextSwap
		Integer executeNextSwap = Integer.valueOf(0);
		return executeNextSwap;
		// End of user code
	}

	// Start of user code (user defined methods for InsertionSort)

	// End of user code

}
