/*******************************************************************************
 * File generated from the UML::iObserver uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of iObserver.
 * 
 * @author 
 */
public interface iObserver {
	// Start of user code (user defined attributes for iObserver)

	// End of user code

	/**
	 * Description of the method update.
	 */
	public void update();

	// Start of user code (user defined methods for iObserver)

	// End of user code

}
