/*******************************************************************************
 * File generated from the UML::Model uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Model.
 * 
 * @author 
 */
public class Model implements iController, iModelPresent {
	/**
	 * Description of the property mSortAlgorithm.
	 */
	private SortAlgorithm mSortAlgorithm = null;

	/**
	 * Description of the property mObserver.
	 */
	public iObserver mObserver = null;

	/**
	 * Description of the property iobserver.
	 */
	public iObserver iobserver = null;

	/**
	 * Description of the property sortalgorithm.
	 */
	public SortAlgorithm sortalgorithm = null;

	// Start of user code (user defined attributes for Model)

	// End of user code

	/**
	 * The constructor.
	 */
	public Model() {
		// Start of user code constructor for Model)
		super();
		// End of user code
	}

	/**
	 * Description of the method notify.
	 */
	public void notify() {
		// Start of user code for method notify
		// End of user code
	}

	// Start of user code (user defined methods for Model)

	// End of user code

}
