/*******************************************************************************
 * File generated from the UML::SortAlgorithm uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of SortAlgorithm.
 * 
 * @author 
 */
public abstract class SortAlgorithm {
	/**
	 * Description of the property mList.
	 */
	private Integer mList = Integer.valueOf(0);

	// Start of user code (user defined attributes for SortAlgorithm)

	// End of user code

	/**
	 * Description of the method executeNextSwap.
	 * @return 
	 */
	public abstract Integer executeNextSwap() throws exIsSorted;

	// Start of user code (user defined methods for SortAlgorithm)

	// End of user code

}
