/*******************************************************************************
 * File generated from the UML::View uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 16. Oktober 2018 15:29:18 MESZ
 *******************************************************************************/

// Start of user code (user defined imports)

// End of user code

/**
 * Description of View.
 * 
 * @author 
 */
public abstract class View implements iObserver {
	/**
	 * Description of the property mModel.
	 */
	protected iModelPresent mModel = null;

	/**
	 * Description of the property imodelpresent.
	 */
	public iModelPresent imodelpresent = null;

	/**
	 * Description of the property controller.
	 */
	public Controller controller = null;

	// Start of user code (user defined attributes for View)

	// End of user code

	/**
	 * The constructor.
	 */
	public View() {
		// Start of user code constructor for View)
		super();
		// End of user code
	}

	/**
	 * Description of the method createController.
	 * @return 
	 */
	public Controller createController() {
		// Start of user code for method createController
		Controller createController = null;
		return createController;
		// End of user code
	}

	// Start of user code (user defined methods for View)

	// End of user code

}
